I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 36, in script
    show nino serious at center with fadeIn(1.0)
  File "game/script.rpy", line 36, in <module>
    show nino serious at center with fadeIn(1.0)
NameError: name 'fadeIn' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 36, in script
    show nino serious at center with fadeIn(1.0)
  File "C:\Program Files\renpy-8.1.3-sdk\renpy\ast.py", line 1674, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Program Files\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Program Files\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 36, in <module>
    show nino serious at center with fadeIn(1.0)
NameError: name 'fadeIn' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
Dish Panic 1.0
Sat Nov  4 22:25:34 2023
